// One-off importer: pulls the mockup's data constants into a TS module. Content is hand-maintained now; keep this for reference.
// Usage: node scripts/gen-data.cjs   (reads docs/index.html, the reference build)
const fs = require('fs'), vm = require('vm'), path = require('path');
const root = path.join(__dirname, '..');
const src = fs.readFileSync(path.join(root, 'docs/index.html'), 'utf8');
const script = src.match(/<script>([\s\S]*)<\/script>/)[1];
const lines = script.split('\n');
const names = ['RAR','COUNTS','PER','KEYS','VAL','BONUS','CYCLE_BASE','AD_LEN','EAT_EVERY','INK','sp','THEMES','RES_DEF','RES_X','STUDY_COST','SHAPES','STORY','SIDE','HYBRIDS','SPLICE_COST','ARTS','TICKETS_PER_DAY','PALETTE','UPT','ART_MAX','GEN_TIER','GEN_DEF','UNLOCK','UNLOCK_NAME'];
let code = '';
for (const n of names){
  const i = lines.findIndex(l => l.startsWith('const ' + n + ' ') || l.startsWith('const ' + n + '='));
  if (i < 0) throw new Error('missing ' + n);
  let j = i, text = lines[i];
  for (;;){ try { new Function(text); break; } catch (e){ j++; if (j >= lines.length) throw new Error('unterminated ' + n); text += '\n' + lines[j]; } }
  code += text + '\n';
}
const ctx = { S: {}, unlocked: () => true, found: () => 0, tierMult: () => 1, Math };
vm.createContext(ctx);
vm.runInContext(code + '\nglobalThis.__out = { RAR, COUNTS, PER, KEYS, VAL, BONUS, CYCLE_BASE, TIER_MULT, UP_MULT, TIER_CYCLE, ASC_LV, ASC_FOUND, RAR_CAP0, RAR_CAP_STEP, SHELF, AD_LEN, AD_CD, BOOST_LEN, WARP, OFFLINE_CAP, EAT_EVERY, EAT_FIRST, THEME: THEMES.bio, RES_DEF, RES_X, STUDY_COST, STUDY_TIME, SHAPES, STORY, SIDE, HYBRIDS, SPLICE_COST, SPLICE_TIME, OB_HP, OB_TIME, ARTS, TICKETS_PER_DAY, PALETTE, UPT, ART_MAX, ART_MERGE, GEN_TIER, GEN_DEF, UNLOCK, UNLOCK_NAME };', ctx);
const d = ctx.__out;
// side-quest gates are closures in the mockup; describe them as data
d.SIDE = d.SIDE.map(q => { const g = q.gate ? q.gate.toString() : ''; const gate = /S\.lv >= 3/.test(g) ? { lv: 3 } : /found\(S\.tier\) < PER - 2/.test(g) ? { undiscovered: 2 } : /unlocked\('(\w+)'\)/.test(g) ? { area: g.match(/unlocked\('(\w+)'\)/)[1] } : null; const { gate: _g, ...rest } = q; return gate ? { ...rest, gate } : rest; });
const j = v => JSON.stringify(v, null, 1).replace(/\n\s*/g, ' ').replace(/Infinity/g, '1e9');
const T = d.THEME;
const out = `// GENERATED by scripts/gen-data.js from docs/index.html. Edit the mockup or the generator, not this file.
/* eslint-disable */
import type { Chapter, SideQuest, Hybrid, Artifact, UpTier, Research, GenPerk, Rarity, TierDef } from './types';

export const RAR: Rarity[] = ${j(d.RAR)};
export const COUNTS: number[] = ${j(d.COUNTS)};
export const PER = ${d.PER};
/** rarity table rows: [level, weights per rarity] */
export const KEYS: [number, number[]][] = ${j(d.KEYS)};
export const VAL: number[] = ${j(d.VAL)};
export const BONUS: number[] = ${j(d.BONUS)};
export const CYCLE_BASE = ${d.CYCLE_BASE}, TIER_MULT = ${d.TIER_MULT}, UP_MULT = ${d.UP_MULT}, TIER_CYCLE = ${d.TIER_CYCLE}, ASC_LV = ${d.ASC_LV}, ASC_FOUND = ${d.ASC_FOUND};
export const RAR_CAP0 = ${d.RAR_CAP0}, RAR_CAP_STEP = ${d.RAR_CAP_STEP}, SHELF = ${d.SHELF};
export const AD_LEN = ${d.AD_LEN}, AD_CD = ${d.AD_CD}, BOOST_LEN = ${d.BOOST_LEN}, WARP = ${d.WARP}, OFFLINE_CAP = ${d.OFFLINE_CAP};
/** seconds between bites by danger level; 1e9 stands for never */
export const EAT_EVERY: number[] = ${j(d.EAT_EVERY.map(v => v === Infinity ? 1e9 : v))};
export const EAT_FIRST: number[] = ${j(d.EAT_FIRST)};
export const SPLICE_COST = ${d.SPLICE_COST}, SPLICE_TIME = ${d.SPLICE_TIME}, OB_HP = ${d.OB_HP}, OB_TIME = ${d.OB_TIME};
export const TICKETS_PER_DAY = ${d.TICKETS_PER_DAY};
export const ART_MAX = ${d.ART_MAX}, ART_MERGE = ${d.ART_MERGE};
export const GEN_TIER = ${d.GEN_TIER};
export const STUDY_COST: number[] = ${j(d.STUDY_COST)};
export const STUDY_TIME: number[] = ${j(d.STUDY_TIME)};
export const SHAPES: string[] = ${j(d.SHAPES)};
export const PALETTE: string[] = ${j(d.PALETTE)};

/** words the game uses for its things */
export const TEXT = ${j({ name: T.name, cur: T.cur, dish: T.dish, drop: T.drop, drops: T.drops, cycling: T.cycling, collect: T.collect, ascend: T.ascend, contain: T.contain })} as const;
export const UP_TEXT: Record<string, [string, string]> = ${j(T.up)};
export const RES_TEXT: Record<string, [string, string]> = ${j({ ...T.res, ...d.RES_X })};
/** hand-named tiers; later tiers are generated from MORE */
export const TIERS: TierDef[] = ${j(T.tiers)};
export const MORE: string[] = ${j(T.more)};

export const RES_DEF: Research[] = ${j(d.RES_DEF)};
export const STORY: Record<number, Chapter> = ${j(d.STORY)};
export const SIDE: SideQuest[] = ${j(d.SIDE)};
export const HYBRIDS: Hybrid[] = ${j(d.HYBRIDS)};
export const ARTS: Artifact[] = ${j(d.ARTS)};
export const UPT: UpTier[] = ${j(d.UPT)};
export const GEN_DEF: GenPerk[] = ${j(d.GEN_DEF)};
/** what opens when: area -> [tier, deliveries made in that tier's chapter] */
export const UNLOCK: Record<string, [number, number]> = ${j(d.UNLOCK)};
export const UNLOCK_NAME: Record<string, string> = ${j(d.UNLOCK_NAME)};
`;
fs.mkdirSync(path.join(root, 'src/data'), { recursive: true });
fs.writeFileSync(path.join(root, 'src/data/generated.ts'), out);
console.log('wrote src/data/generated.ts', out.length, 'bytes');
